parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.eslint.json

env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier/@typescript-eslint
  - prettier # must go last, to turn off some previous rules

rules:
  prefer-arrow-callback: error
  func-names: off
  no-use-before-define: off
  require-await: error
  '@typescript-eslint/no-use-before-define': off

ignorePatterns:
  - dist
