openapi: 3.0.0
info:
  title: Example OpenApi 3 spec
  description: Has various paths with responses to use in testing
  version: 0.1.0
paths:
  /endpointPath:
    get:
      responses:
        204:
          $ref: '#/components/responses/NonExistentResponse'
